v2.1.0
epispot/epispot pull request #27
Opened 2021-03-29 00:32 UTC by quantum9Innovation

# Merge v2.1.0 from `nightly` into `master`
___

## New Feature
Introducing pre-compiled models!
Compile a common model with just one function call to `epispot.pre`.
## Known Issues
Code coverage is now @ 98% :fireworks:
However, a few new errors were discovered in tests; see
 - #20 
 - #21 
## Code Breakdown
Merged the `epispot/` and `tests/` directories from `nightly` into `v2.1.0`
Ex:
 - epispot/pre.py
    - Use this to define pre-compiled models!
  - epispot/*
     - Marked code with `# pragma: no cover` to indicate exemption from code coverage
 - tests/CI/
    - Added new tests for `pre.py`
    - Added new tests to increase code coverage
 - .github/workflows/build.yml
    - Trigger code coverage on change to main package
    - Added new tests

2021-03-29 00:34 UTC, quantum9Innovation commented
LGTM alerts will be fixed in a future release: **ignore for now**

2021-03-29 00:35 UTC, quantum9Innovation commented
Waiting on CodeQL and LGTM (if there are any new issues they will be fixed in a later release)

2021-03-30 16:43 UTC, quantum9Innovation commented
@Quantalabs ready to merge after review

2021-04-02 22:27 UTC, Quantalabs requested changes
Comment on `coverage.yml` workflow.

2021-04-02 22:27 UTC, Quantalabs commented on .github/workflows/coverage.yml
>        - codecov
There is no "codecov" branch. Change this to "main" if you are merging this into main.

2021-04-03 00:32 UTC, merged