Added a CLI
epispot/epispot pull request #38
Opened 2021-04-11 22:18 UTC by quantum9Innovation

# Basic CLI Structure Implemented
___

## New Feature
This PR adds a basic built-in CLI to epispot nightly that comes preinstalled with setup.py. The keyword to initiate it is `epispot` followed by a command. Currently the only available command is `about`. The shell uses `Fire` and `termcolor` as dependencies although it can run without `termcolor` by suppressing color (see the `__color__` flag). To test the shell, run:
```shell
$ epispot about
>>> Epispot was invoked via the epispot CLI
>>> Path: /home/user/anaconda3/lib/python3.8/site-packages/epispot_nightly-2.1.1.1-py3.8.egg/EGG-INFO/scripts
>>> Version: shell-v0.1.0-alpha epispot-v2.1.1.1
>>> Color output enabled (True/False): True

```
## Known Issues
- Coverage does not work on CLI scripts.
- Planning on adding an enhancement to run models from the CLI; will require the addition of automatic 
parameter substitutions that will be implemented in another branch.
## Code Breakdown

 - .coveragerc
    - Added bin/ as a directory however still not implemented in codecov reports (issue)
 - .github/workflows
    - Added to support build tests for CLI
    - coverage.yml
        - Added more verbosity for issue solving related to code coverage reporting
- CHANGELOG.md
    - Added a CHANGELOG to track progress on the nightly package
- README.md
    - Removed Release Notes on README.md to create CHANGELOG.md
- bin/requirements.txt
    - Added separate CLI requirements (Fire, termcolor (optional))
- requirements.txt
    - Removed unnecessary requirements (sphinx)
- setup.py
    - Added `scripts` indicator to add `epispot` to the command line
## Additional Notes
Similar to branch #cli
Ideally merge when:
 - Code and implementation has been thoroughly reviewed
 - New workflows have been approved by @Quantalabs 's review
**Ignoring:**
 - LGTM, CodeFactor, and other code quality checks (except built-in GitHub CodeQL)
     - Currently transitioning to Deepsource

2021-04-11 22:19 UTC, quantum9Innovation commented
Ready to merge after workflow approvals from @Quantalabs

2021-04-12 02:11 UTC, Quantalabs requested changes

2021-04-12 02:11 UTC, Quantalabs commented on .github/workflows/build.yml
> +        python setup.py install
Instead of installing, it's better to use `develop`.

```suggestion
        python setup.py develop
```

2021-04-12 02:11 UTC, Quantalabs commented on bin/epispot
> +        color=__color__
Why are you using a library like termcolor for terminal string styling? You can use the python built-in ANSI escape codes which are much more customizable, such as _italics_ or underlined

2021-04-12 02:11 UTC, Quantalabs commented on setup.py
> +    scripts=['bin/epispot'],
You could also use `console_scripts` which will allow for more customizable command names.

```suggestion
    console_scripts=[
         'epi: bin/epispot'
    ]
```

2021-04-12 02:15 UTC, Quantalabs commented on setup.py
> +    scripts=['bin/epispot'],
You should check though that this works with classes.

2021-04-12 02:19 UTC, Quantalabs commented on setup.py
> +    scripts=['bin/epispot'],
It seems this doesn't work with classes. Ignore this suggestion.

2021-04-12 17:53 UTC, quantum9Innovation commented
Using #40 instead; keeping this PR as a backup in case anything goes wrong.

2021-04-12 19:34 UTC, Quantalabs commented
Will re-open if any bad problems turn up in #40

2021-04-12 21:03 UTC, merged