Initialization Testing
epispot/epispot pull request #50
Opened 2021-05-13 02:53 UTC by quantum9Innovation

# Adds initialization testing to package
From PR #48, after PR #49 
___

## New Feature
Adds sanity and dependency checks to the `epispot/__init__.py` file and adds classifiers and other metadata to both `setup.py` and `setup-nightly.py`.
## Known Issues
No known issues.
## Code Breakdown
 - epispot/\_\_init\_\_.py
     - Sanity checks
     - Dependency checks
     - Increased package documentation
         - Ported from `README.md`
 - release.py
     - Updated to be compatible with new initialization file
 - setup.py, setup-nightly.py
     - Adds classifiers
     - Adds more URLs

2021-05-14 19:11 UTC, quantum9Innovation commented
## Merging Guidelines
Test analysis

---

Build → passing ✅ 
Code Coverage → **not failing**\* (no change 🏳️ )
CodeQL → passing ✅ 
DeepSource → passing ✅ 
LGTM→ failing ❌ 

*Code coverage reporting on the `master` branch is currently incorrect. This will be fixed in a later PR

Merge after
 - [ ] LGTM fixed
 - [ ] Review from @Quantalabs

2021-05-16 00:56 UTC, quantum9Innovation commented
## Update
Waiting for @Quantalabs before fixing LGTM alerts

2021-05-16 03:01 UTC, quantum9Innovation commented
> ## Update
> Waiting for @Quantalabs before fixing LGTM alerts

@Quantalabs

2021-05-16 03:17 UTC, Quantalabs requested changes

2021-05-16 03:17 UTC, Quantalabs commented on epispot/__init__.py
> +Thank you also to all [GitHub contributors](https://www.github.com/epispot/epispot/insights/contributors)
Why do you have all this? Use:
```rst
.. include:: ../README.md
```

2021-05-16 03:17 UTC, Quantalabs commented on epispot/__init__.py
> +_sanity_check()  # complete installation
You shouldn't have the sanity check after running it.
```suggestion
_sanity_check()  # complete installation
del _sanity_check()
```

2021-05-16 03:17 UTC, Quantalabs commented on epispot/__init__.py
> +_dependency_check()  # check for uninstalled dependencies
You shouldn't have the dependency check after running it.
```suggestion
_dependency_check()  # check for uninstalled dependencies
del _dependency_check()
```

2021-05-17 00:01 UTC, quantum9Innovation commented
# Merge Process
 - [ ] CodeQL must pass :heavy_check_mark: 
 - [ ] LGTM must pass :heavy_check_mark: 
 - [ ] Approving review from @Quantalabs :heavy_check_mark: 

---

Merge method undetermined as of yet

2021-05-17 05:30 UTC, Quantalabs approved these changes
Looks good

2021-05-17 05:30 UTC, Quantalabs commented
> Looks good

Do fix the LGTM alert however

2021-05-17 21:45 UTC, merged