Fix travis-ci
epispot/epispot pull request #64
Opened 2021-06-15 04:45 UTC by Quantalabs

The bug in the travis ci code happens because we install SciencePlots and matplotlib at the same time, so when SciencePlots tries to install the styles to matplotlib, it errors as there is no way to install them into matplotlib, which hasn't been installed.

## SOLUTION
We first install all the developer requirements, which no longer include SciencePlots, and then separately, we install SciencePlots.

2021-06-15 04:50 UTC, quantum9Innovation requested changes
Don't touch any of the requirements files; those will be used by package developers and must stay intact.

2021-06-15 04:50 UTC, quantum9Innovation commented on requirements-dev.txt
> -SciencePlots
Keep this

2021-06-16 00:26 UTC, Quantalabs commented
This should work now, with SciencePlots on the `requirements` file.

2021-06-16 00:40 UTC, quantum9Innovation approved these changes

2021-06-16 00:40 UTC, merged